receivers:
  - name: "discord"
    discord_configs:
      - webhook_url: "${DISCORD_WEBHOOK_URL}"
        send_resolved: true

route:
  receiver: "discord"
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 5m

inhibit_rules:
  - source_matchers:
      - severity = "critical"
    target_matchers:
      - severity = "warning"
    equal: ["alertname"]
