receivers:
  - name: "discord"
    webhook_configs:
      - url: "http://alert-relay:8010/alert"
        send_resolved: true

route:
  receiver: "discord"
  group_by: ["alertname"]
  group_wait: 5s
  group_interval: 15s
  repeat_interval: 5m

inhibit_rules:
  - source_matchers:
      - severity = "critical"
    target_matchers:
      - severity = "warning"
    equal: ["alertname"]
